### ISSUE TITLE
🚀 Roadmap

### ISSUE THREAD

**Issue by tiangolo** [tiangolo/full-stack-fastapi-postgresql#541]
## Description

This is a tentative roadmap, I will update it as things evolve. Some things might be discarded, others might be added later. I didn't want to make it fully public as it could raise expectations, but it seems it would be more beneficial for the community to know all the ideas and objectives.

Work on this is alternated (and sometimes mixed) with work on FastAPI, Typer, SQLModel, Asyncer, and others.

In fact, I created SQLModel for this project. 🚀 

Answering questions, issues, and PRs is also intermixed with this, but as in some cases one of these features would solve several issues or questions, or potentially solve something done by one or more PRs, in many cases I focus on this a bit more than on answering specific issues, questions, PRs.

## Maintenance

The word "maintenance" or "maintainer" doesn't have a very strict definition, and it probably varies a lot from perspective.

A lot of the work related to maintaining FastAPI is done by contributors by answering questions, reviewing PRs, etc.

You can help me ensure each existing PR is in shape (has tests, solves the problem, etc.). Make sure you filter out the translation PRs (most of them) unless you speak the language and can review them.

## Security

When there are security issues, those are handled with the highest priority. Those are normally not handled in issues and PRs but in emails, it's not public until the security disclosure is made, in most cases (always, up to now) with the version that fixes them.

## Roadmap

Now, here's the current high-level tentative roadmap:

- [ ] Upgrade to the latest FastAPI.
- [ ] Upgrade to Pydantic v2.
- [ ] Migration from SQLAlchemy to SQLModel.
- [ ] Refactor and simplification of most of the code, a lot of the complexity won't be necessary anymore.
- [ ] Migrate from Vue.js 2 to React with hooks and TypeScript.
- [ ] Move from Docker Swarm Model to Kubernetes.
- [ ] GitHub Actions for CI.

All this is intermixed with reviews for PRs, issues, and discussions.

**Comment by PhilippWu** [comment]
Great!!!! I Love your Templates. And with react IT would even be better. Ist there a plan or a Chance mongodb will be integrated in the Future?

**Comment by Antony-Jia** [comment]
It's so Great!!!

**Comment by jakeecolution** [comment]
@PhilippWu - Using mongodb isn't too difficult to add especially with the [`beanie`](https://beanie-odm.dev/) module which makes defining Collection simple.

**Comment by omarcevi** [comment]
I was wondering if there was a time frame for next release?

**Comment by saffist3r** [comment]
Move from Docker Swarm Model to Kubernetes. <--------- THIS

**Comment by KimNikB** [comment]
Hi! Is there a timeline for this Roadmap? I was thinking of using this template for a project but it might be a bit to urgent...

**Comment by jakeecolution** [comment]
@KimNikB - I suggest using the backend as a scaffolding but you'll need to make your own. Python 3.7 was depreciated and other things make it unusable as it is but it is easy to build up your own backend.

Search the issues

**Comment by 7uperior** [comment]
SQLModel is using Pydantic v1 => this project is using sqlalchemy v2 instead of SQLModel

**Comment by VivienGiraud** [comment]
Hi @tiangolo !
Any chance to see FastUI landing to you template?

**Comment by zuzanabi** [comment]
> ## Description
> 
> This is a tentative roadmap, I will update it as things evolve. Some things might be discarded, others might be added later. I didn't want to make it fully public as it could raise expectations, but it seems it would be more beneficial for the community to know all the ideas and objectives.
> 
> Work on this is alternated (and sometimes mixed) with work on FastAPI, Typer, SQLModel, Asyncer, and others.
> 
> In fact, I created SQLModel for this project. 🚀
> 
> Answering questions, issues, and PRs is also intermixed with this, but as in some cases one of these features would solve several issues or questions, or potentially solve something done by one or more PRs, in many cases I focus on this a bit more than on answering specific issues, questions, PRs.
> ## Maintenance
> 
> The word "maintenance" or "maintainer" doesn't have a very strict definition, and it probably varies a lot from perspective.
> 
> A lot of the work related to maintaining FastAPI is done by contributors by answering questions, reviewing PRs, etc.
> 
> You can help me ensure each existing PR is in shape (has tests, solves the problem, etc.). Make sure you filter out the translation PRs (most of them) unless you speak the language and can review them.
> ## Security
> 
> When there are security issues, those are handled with the highest priority. Those are normally not handled in issues and PRs but in emails, it's not public until the security disclosure is made, in most cases (always, up to now) with the version that fixes them.
> ## Roadmap
> 
> Now, here's the current high-level tentative roadmap:
> 
>     * [ ]  Upgrade to the latest FastAPI.
> 
>     * [ ]  Migration from SQLAlchemy to SQLModel.
> 
>     * [ ]  Upgrade to Pydantic v2.
> 
>     * [ ]  Refactor and simplification of most of the code, a lot of the complexity won't be necessary anymore.
> 
>     * [ ]  Migrate from Vue.js 2 to React with hooks and TypeScript.
> 
>     * [ ]  Move from Docker Swarm Model to Kubernetes.
> 
>     * [ ]  GitHub Actions for CI.
> 
> 
> All this is intermixed with reviews for PRs, issues, and discussions.

**Comment by renja-g** [comment]
I have a question, is this Roadmap still up to date or are there already some checked?
> ## Roadmap
> Now, here's the current high-level tentative roadmap:
> 
> * [ ]  Upgrade to the latest FastAPI.
> * [ ]  Migration from SQLAlchemy to SQLModel.
> * [ ]  Upgrade to Pydantic v2.
> * [ ]  Refactor and simplification of most of the code, a lot of the complexity won't be necessary anymore.
> * [ ]  Migrate from Vue.js 2 to React with hooks and TypeScript.
> * [ ]  Move from Docker Swarm Model to Kubernetes.
> * [ ]  GitHub Actions for CI.
> 
> All this is intermixed with reviews for PRs, issues, and discussions.

**Comment by fabifont** [comment]
Hi @tiangolo, what is the current progress of those things?
- Upgrade to the latest FastAPI
- Migration from SQLAlchemy to SQLModel
- Upgrade to Pydantic v2

Can you provide an ETA?

**Comment by R-shubham** [comment]
Hi @PhilippWu , here is the MongoDB version of the app generator

https://github.com/mongodb-labs/full-stack-fastapi-mongodb

It currently uses ODMantic as an ODM.

**Comment by dickermoshe** [comment]
Oh yeah!, stuff is happening!

**Comment by tiangolo** [comment]
Hello everyone! This is now done! :tada: 

https://github.com/tiangolo/full-stack-fastapi-template/releases/tag/0.6.0

Some additional notes:

---

This now uses the latest FastAPI, Pydantic, SQLModel. :rocket: 

In fact, there were features added to SQLModel for this project. :sunglasses: 

The code is much simpler now, it should be easier to understand, evolve, refactor, while keeping all the same flexibility if not more, but much more powerful and safer.

The frontend now uses React with Vite, TypeScript, TanStack Query, TanStack Router, Chakra UI, no additional state management, an auto-generated frontend client/SDK, dark mode support, and other things. There were many intermediate iterations trying out different alternatives and combinations of libraries to get to this point and these decisions. :rocket: 

The project now works as is, if you clone it, you can start using it. You can also use generation with Copier (instead of Cookiecutter), mainly to populate the configurations in `.env`.

There is no more support nor recommendation to use Docker Swarm Mode. Instead there are docs and files to deploy using Docker Compose, which now supports production deployments. This means that the Docker Compose files were significantly simplified and should be easier to understand and use.

Deploying to different platforms, like cloud services or Kubernetes is out of scope for this project, as any deployment in a system like that would depend a lot on the other components of the cluster or cloud provider, for example, there's no simple way to include Kubernetes files here without making lots of assumptions about the cluster. So, instead, there are files and documentation to make a simple deployment using Docker Compose, which can help as a starting point for each team to adjust to their deployment systems.

There is now support for GitHub Actions. The tests run in CI, including tracking test coverage, the coverage files can be tracked and the coverage badge can be set up with Smokeshow: https://github.com/samuelcolvin/smokeshow

pgAdmin was replaced with Adminer.

Celery and Flower were removed, this project doesn't really use that, and I currently wouldn't go for them if I needed that type of capability, once I figure out the alternative I would recommend I would add it to this repo too. You can read more details (and some of the options I want to try) in the PR: https://github.com/tiangolo/full-stack-fastapi-template/pull/694

---

There will be of course more features, fixes, etc. But the project is now ready again to be used as the template for your apps. I'm very happy and proud of the current state of the project! And I look forward to all you will build with it. :rocket: 

Thanks a lot for all the work to @alejsdev and @estebanx64 :bow:
